"""create invoice items table

Revision ID: 3b9a4a001431
Revises: c19f3e28549f
Create Date: 2026-08-10 23:47:50.206932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9a4a001431'
down_revision: Union[str, Sequence[str], None] = 'c19f3e28549f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    # ### end Alembic commands ###
