"""add manufacture invoice number counter

Revision ID: 3efd0c13c529
Revises: b4f4d0f9a5d1
Create Date: 2026-08-31 02:11:23.848505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efd0c13c529'
down_revision: Union[str, Sequence[str], None] = 'b4f4d0f9a5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacture_invoice_number_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manufacture_invoice_number_counters')
    # ### end Alembic commands ###
