"""create invoices table

Revision ID: 76a3d4bc5465
Revises: 71d0a75348b2
Create Date: 2026-08-10 21:09:15.287097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a3d4bc5465'
down_revision: Union[str, Sequence[str], None] = '71d0a75348b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('eway_bill_number', sa.String(length=50), nullable=True),
    sa.Column('delivery_note', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('supplier_reference', sa.String(length=200), nullable=True),
    sa.Column('other_references', sa.String(length=200), nullable=True),
    sa.Column('buyer_order_number', sa.String(length=100), nullable=True),
    sa.Column('buyer_order_date', sa.Date(), nullable=True),
    sa.Column('dispatch_document_number', sa.String(length=100), nullable=True),
    sa.Column('delivery_note_date', sa.Date(), nullable=True),
    sa.Column('dispatched_through', sa.String(length=150), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('lr_rr_number', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('terms_of_delivery', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
